### ISSUE TITLE
WebSocket URI must be absolute IllegalArgumentException

### ISSUE THREAD

**Issue by rnayabed** [Twasi/websocket-obs-java#26]
I am getting this error when i try to connect to `ws://localhost:4444/`
Not just this address, but anything throws this 

```
Failed to setup connection with OBS.
java.lang.IllegalArgumentException: WebSocket URI must be absolute
        at org.eclipse.jetty.websocket.client@9.4.35.v20201120/org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:338)
        at org.eclipse.jetty.websocket.client@9.4.35.v20201120/org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:312)
        at obs.websocket.java@1.0.5/net.twasi.obsremotejava.OBSRemoteController.connect(OBSRemoteController.java:64)
        at obs.websocket.java@1.0.5/net.twasi.obsremotejava.OBSRemoteController.<init>(OBSRemoteController.java:39)
        at obs.websocket.java@1.0.5/net.twasi.obsremotejava.OBSRemoteController.<init>(OBSRemoteController.java:44)
        at com.StreamPi.OBSSuite.Mother@1.0.0/com.StreamPi.OBSSuite.Mother.OBSActionConnectionTask.call(OBSActionConnectionTask.java:38)
        at com.StreamPi.OBSSuite.Mother@1.0.0/com.StreamPi.OBSSuite.Mother.OBSActionConnectionTask.call(OBSActionConnectionTask.java:12)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

This is very weird.

**Comment by rnayabed** [comment]
sorry im the dumbest person on earth

**Comment by TinaTiel** [comment]
No worries!
Just out of curiosity, what were you doing to replicate this problem initially?

**Comment by rnayabed** [comment]
> No worries!
> Just out of curiosity, what were you doing to replicate this problem initially?

My password was the URL and my URL was the password :P
